# Generated by Django 3.2.16 on 2023-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='teacher_name',
            field=models.CharField(choices=[('0', 'Mr Oakley'), ('1', 'Mrs Brundle'), ('2', 'Mr Simons'), ('3', 'Miss Baxter'), ('4', 'Mrs Shepard'), ('5', 'Miss Edwards')], default='0', max_length=80),
        ),
    ]
