# Generated by Django 3.2.16 on 2023-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_appointment_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('teacher_name', 'date', 'time')},
        ),
    ]
